In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

Each element of the Product matrix AB can be calculated as follows:

AB11 = -1×0 + 2×0 + 3×2 = 6
AB12 = -1×2 + 2×2 + 3×9 = 29
AB13 = -1×1 + 2×-8 + 3×-1 = -20
AB21 = 4×0 + -5×0 + 6×2 = 12
AB22 = 4×2 + -5×2 + 6×9 = 52
AB23 = 4×1 + -5×-8 + 6×-1 = 38
AB31 = 7×0 + 8×0 + -9×2 = -18
AB32 = 7×2 + 8×2 + -9×9 = -51
AB33 = 7×1 + 8×-8 + -9×-1 = -48

product_ab = np.array([[6,29,-20],
                        [12,52,38],
                        [-18,-51,-48]]

In [2]:
import numpy as np
a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
np.matmul(a, b)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [3]:
print(f'The calculation of 0th row of matrix a and that of matrix b is:', a_ndarray[0,0]*b_ndarray[0,0] + a_ndarray[0,1]*b_ndarray[1,0] + a_ndarray[0,2]*b_ndarray[2,0])

The calculation of 0th row of matrix a and that of matrix b is: 6


In [4]:
import numpy as np
def matrix_multiplication(matrix_a, matrix_b):
    mat = np.zeros(9)
    product = mat.reshape(3,3)
    
    for x in range(len(matrix_a)):
        for y in range(len(matrix_b)):
            for z in range(len(matrix_b)):
                product[x][y] += matrix_a[x][z] * matrix_b[z][y]
    print(product)
matrix_multiplication(a_ndarray, b_ndarray)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [5]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

if d_ndarray.shape[0] == e_ndarray.shape[1]:
    print(product_of_matrix(d_ndarray, e_ndarray))
else:           
    print("Hey! those matrices are not aligned")

Hey! those matrices are not aligned


In [6]:
print('product of matrix when transposed is:')
np.dot(a_ndarray.T,b_ndarray)

product of matrix when transposed is:


array([[ 14,  69, -40],
       [ 16,  66,  34],
       [-18, -63, -36]])